---
#
# Notice my settings are for a slimmelezer+
#
substitutions:
  device_name: p1reader

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://basn/esphome-p1reader
    components: [p1reader]

wifi:
  #  use_address: $name
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    #password: !secret wifi_fallback

captive_portal:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart
  
# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  id: uart_bus
  tx_pin: D8
  rx_pin: D7
  baud_rate: 115200

# This is for Aidon 6442SE
# Tekniska Verken in Linköping, which use the older
# Branschstandard (1.2) where the data is HDLC-formatted  
# Used for example in Karlstad Energi

sensor:
- platform: custom
  lambda: |-
    auto meter_sensor = new P1Reader(id(uart_bus));
    App.register_component(meter_sensor);
    return {
      meter_sensor->cumulativeActiveImport,
      meter_sensor->cumulativeActiveExport,
      meter_sensor->cumulativeReactiveImport,
      meter_sensor->cumulativeReactiveExport,
      meter_sensor->momentaryActiveImport,
      meter_sensor->momentaryActiveExport,
      meter_sensor->momentaryReactiveImport,
      meter_sensor->momentaryReactiveExport,
      meter_sensor->momentaryActiveImportL1,
      meter_sensor->momentaryActiveExportL1,
      meter_sensor->momentaryActiveImportL2,
      meter_sensor->momentaryActiveExportL2,
      meter_sensor->momentaryActiveImportL3,
      meter_sensor->momentaryActiveExportL3,
      meter_sensor->momentaryReactiveImportL1,
      meter_sensor->momentaryReactiveExportL1,
      meter_sensor->momentaryReactiveImportL2,
      meter_sensor->momentaryReactiveExportL2,
      meter_sensor->momentaryReactiveImportL3,
      meter_sensor->momentaryReactiveExportL3,
      meter_sensor->voltageL1,
      meter_sensor->voltageL2,
      meter_sensor->voltageL3,
      meter_sensor->currentL1,
      meter_sensor->currentL2,
      meter_sensor->currentL3
    };
  sensors:
  - name: "Cumulative Active Import"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"

  - name: "Cumulative Active Export"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"

  - name: "Cumulative Reactive Import"
    unit_of_measurement: kvarh
    accuracy_decimals: 3
    state_class: "total_increasing"

  - name: "Cumulative Reactive Export"
    unit_of_measurement: kvarh
    accuracy_decimals: 3
    state_class: "total_increasing"

  - name: "Momentary Active Import"
    unit_of_measurement: kWh
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Export"
    unit_of_measurement: kWh
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Reactive Import"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Export"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Active Import Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Export Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Import Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Export Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Import Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Active Export Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 2
    state_class: "measurement"
    device_class: "power"

  - name: "Momentary Reactive Import Phase 1"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Export Phase 1"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Import Phase 2"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Export Phase 2"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Import Phase 3"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Momentary Reactive Export Phase 3"
    unit_of_measurement: var
    accuracy_decimals: 2
    state_class: "measurement"

  - name: "Voltage Phase 1"
    unit_of_measurement: V
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "voltage"

  - name: "Voltage Phase 2"
    unit_of_measurement: V
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "voltage"

  - name: "Voltage Phase 3"
    unit_of_measurement: V
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "voltage"

  - name: "Current Phase 1"
    unit_of_measurement: A
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "current"

  - name: "Current Phase 2"
    unit_of_measurement: A
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "current"

  - name: "Current Phase 3"
    unit_of_measurement: A
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "current"
